/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BulkChangeDocumentsForProjectOkEnum,
  BulkChangeDocumentsForProjectParams,
  DocumentBulk,
  DocumentBulkResult,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить до 100 документов одним действием; каждый записывается отдельно под своей ревизией, отказ одного не откатывает остальные
 *
 * @tags entities
 * @name BulkChangeDocumentsForProject
 * @summary Изменить до 100 документов одним действием; каждый записывается отдельно под своей ревизией, отказ одного не откатывает остальные
 * @request POST:/api/v1/projects/{project}/entities/document-bulk
 */
export const bulkChangeDocumentsForProject = (
  http: ApiRequestClient,
  { project }: BulkChangeDocumentsForProjectParams,
  data: DocumentBulk,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: BulkChangeDocumentsForProjectOkEnum;
      /** Частичный результат массовой операции */
      data: DocumentBulkResult;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/document-bulk`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
