/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskSaved,
  ChangeCriterion,
  ChangeTaskCriterionForProjectOkEnum,
  ChangeTaskCriterionForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Добавить, изменить, удалить или отметить критерий с проверкой ревизии
 *
 * @tags kanban
 * @name ChangeTaskCriterionForProject
 * @summary Добавить, изменить, удалить или отметить критерий с проверкой ревизии
 * @request POST:/api/v1/projects/{project}/board-tasks/{reference}/criteria
 */
export const changeTaskCriterionForProject = (
  http: ApiRequestClient,
  { reference, project }: ChangeTaskCriterionForProjectParams,
  data: ChangeCriterion,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: ChangeTaskCriterionForProjectOkEnum;
      data: BoardTaskSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}/criteria`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
