/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CreateReleaseOkEnum,
  PlanningSaved,
  SaveRelease,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать релиз с выбранными планами; статус released проверяет готовность и фиксирует выпуск
 *
 * @tags releases
 * @name CreateRelease
 * @summary Создать релиз с выбранными планами; статус released проверяет готовность и фиксирует выпуск
 * @request POST:/api/v1/releases
 */
export const createRelease = (
  http: ApiRequestClient,
  data: SaveRelease,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: CreateReleaseOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/releases`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
