/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  CreatePlan,
  CreatePlanOkEnum,
  PlanningSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать черновик плана и атомарно согласовать его связи
 *
 * @tags plans
 * @name CreatePlan
 * @summary Создать черновик плана и атомарно согласовать его связи
 * @request POST:/api/v1/plans
 */
export const createPlan = (
  http: ApiRequestClient,
  data: CreatePlan,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: CreatePlanOkEnum;
      data: PlanningSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/plans`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
