/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  BoardTaskSaved,
  CreateBoardTask,
  CreateBoardTaskForProjectOkEnum,
  CreateBoardTaskForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Создать задачу доски; requestId служит корреляции и не предотвращает повторное создание
 *
 * @tags kanban
 * @name CreateBoardTaskForProject
 * @summary Создать задачу доски; requestId служит корреляции и не предотвращает повторное создание
 * @request POST:/api/v1/projects/{project}/board-tasks
 */
export const createBoardTaskForProject = (
  http: ApiRequestClient,
  { project }: CreateBoardTaskForProjectParams,
  data: CreateBoardTask,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: CreateBoardTaskForProjectOkEnum;
      data: BoardTaskSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
