/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  DeleteEntity,
  DeleteEntityForProjectOkEnum,
  DeleteEntityForProjectParams,
  EntityDeleted,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Удалить подтверждённый каскад и снять внешние связи с проверкой версии; requestId служит корреляции
 *
 * @tags entities
 * @name DeleteEntityForProject
 * @summary Удалить подтверждённый каскад и снять внешние связи с проверкой версии; requestId служит корреляции
 * @request POST:/api/v1/projects/{project}/entities/delete
 */
export const deleteEntityForProject = (
  http: ApiRequestClient,
  { project }: DeleteEntityForProjectParams,
  data: DeleteEntity,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: DeleteEntityForProjectOkEnum;
      data: EntityDeleted;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/delete`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
