/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskCommentForProjectOkEnum,
  GetTaskCommentForProjectParams,
  TaskComment,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Полный Markdown сообщения с автором и временем
 *
 * @tags kanban
 * @name GetTaskCommentForProject
 * @summary Полный Markdown сообщения с автором и временем
 * @request GET:/api/v1/projects/{project}/board-tasks/{reference}/comments/{entryId}
 */
export const getTaskCommentForProject = (
  http: ApiRequestClient,
  { entryId, reference, project }: GetTaskCommentForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskCommentForProjectOkEnum;
      data: TaskComment;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/board-tasks/${reference}/comments/${entryId}`,
    method: "GET",
    format: "json",
    ...params,
  });
