/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskPlanMembershipsForProjectOkEnum,
  GetTaskPlanMembershipsForProjectParams,
  PlanMemberships,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Текущее участие задачи в планах
 *
 * @tags plans
 * @name GetTaskPlanMembershipsForProject
 * @summary Текущее участие задачи в планах
 * @request GET:/api/v1/projects/{project}/plans/task-memberships/{reference}
 */
export const getTaskPlanMembershipsForProject = (
  http: ApiRequestClient,
  { reference, project, ...query }: GetTaskPlanMembershipsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskPlanMembershipsForProjectOkEnum;
      data: PlanMemberships;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/plans/task-memberships/${reference}`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
