/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntityDocumentsPage,
  GetEntityDocumentsForProjectOkEnum,
  GetEntityDocumentsForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Прочитать материалы, прикреплённые непосредственно к сущности любого вида: связи relations и совместимые links
 *
 * @tags entities
 * @name GetEntityDocumentsForProject
 * @summary Прочитать материалы, прикреплённые непосредственно к сущности любого вида: связи relations и совместимые links
 * @request GET:/api/v1/projects/{project}/entities/documents
 */
export const getEntityDocumentsForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetEntityDocumentsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetEntityDocumentsForProjectOkEnum;
      data: EntityDocumentsPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/documents`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
