/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetTaskCommentsOkEnum,
  GetTaskCommentsParams,
  TaskCommentsPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Сообщения обсуждения без полного Markdown, по 20 с курсором
 *
 * @tags kanban
 * @name GetTaskComments
 * @summary Сообщения обсуждения без полного Markdown, по 20 с курсором
 * @request GET:/api/v1/board-tasks/{reference}/comments
 */
export const getTaskComments = (
  http: ApiRequestClient,
  { reference, ...query }: GetTaskCommentsParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetTaskCommentsOkEnum;
      data: TaskCommentsPage;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}/comments`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
