/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductOverviewMetricForProjectOkEnum,
  GetProductOverviewMetricForProjectParams,
  ProductOverviewMetricPage,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Страница полной выборки метрики оператора обзора (snapshot.operator) с продолжением на неизменном срезе
 *
 * @tags product
 * @name GetProductOverviewMetricForProject
 * @summary Страница полной выборки метрики оператора обзора (snapshot.operator) с продолжением на неизменном срезе
 * @request GET:/api/v1/projects/{project}/product/overview/metrics/{metric}
 */
export const getProductOverviewMetricForProject = (
  http: ApiRequestClient,
  { metric, project, ...query }: GetProductOverviewMetricForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductOverviewMetricForProjectOkEnum;
      /** Постраничная детализация метрики оператора обзора */
      data: ProductOverviewMetricPage;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/product/overview/metrics/${metric}`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
