/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  DocumentFacets,
  GetDocumentFacetsForProjectOkEnum,
  GetDocumentFacetsForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Посчитать документы библиотеки по разделам, тегам, форматам, типам, состояниям и системным представлениям по полным данным проекта
 *
 * @tags entities
 * @name GetDocumentFacetsForProject
 * @summary Посчитать документы библиотеки по разделам, тегам, форматам, типам, состояниям и системным представлениям по полным данным проекта
 * @request GET:/api/v1/projects/{project}/entities/document-facets
 */
export const getDocumentFacetsForProject = (
  http: ApiRequestClient,
  { project, ...query }: GetDocumentFacetsForProjectParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetDocumentFacetsForProjectOkEnum;
      /** Счётчики каталога документов по полным данным выбранного проекта, не по странице */
      data: DocumentFacets;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/document-facets`,
    method: "GET",
    query: query,
    format: "json",
    ...params,
  });
