/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetProductOverviewOkEnum,
  ProductOverview,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Компактная карта продукта без полных текстов
 *
 * @tags product
 * @name GetProductOverview
 * @summary Компактная карта продукта без полных текстов
 * @request GET:/api/v1/product/overview
 */
export const getProductOverview = (
  http: ApiRequestClient,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetProductOverviewOkEnum;
      /** Обзор продукта: прежняя карта и общий согласованный срез проекта */
      data: ProductOverview;
    },
    ApiFailure
  >({
    path: `/api/v1/product/overview`,
    method: "GET",
    format: "json",
    ...params,
  });
