/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GetReleaseOkEnum,
  GetReleaseParams,
  ReleaseSummary,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";

/**
 * @description Реквизиты релиза и текущая готовность выбранных планов
 *
 * @tags releases
 * @name GetRelease
 * @summary Реквизиты релиза и текущая готовность выбранных планов
 * @request GET:/api/v1/releases/{reference}
 */
export const getRelease = (
  http: ApiRequestClient,
  { reference }: GetReleaseParams,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: GetReleaseOkEnum;
      data: ReleaseSummary;
    },
    ApiFailure
  >({
    path: `/api/v1/releases/${reference}`,
    method: "GET",
    format: "json",
    ...params,
  });
