/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  GraphMutation,
  GraphSaved,
  MutateGraphOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Атомарно установить, изменить или отозвать отношения; requestId служит корреляции, устаревшая версия отклоняется
 *
 * @tags graph
 * @name MutateGraph
 * @summary Атомарно установить, изменить или отозвать отношения; requestId служит корреляции, устаревшая версия отклоняется
 * @request POST:/api/v1/graph
 */
export const mutateGraph = (
  http: ApiRequestClient,
  data: GraphMutation,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: MutateGraphOkEnum;
      data: GraphSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/graph`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
