/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  PublishTaskComment,
  PublishTaskCommentOkEnum,
  PublishTaskCommentParams,
  TaskCommentSaved,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Опубликовать сообщение с заданным автором без изменения ревизии задачи; повтор может создать новое сообщение
 *
 * @tags kanban
 * @name PublishTaskComment
 * @summary Опубликовать сообщение с заданным автором без изменения ревизии задачи; повтор может создать новое сообщение
 * @request POST:/api/v1/board-tasks/{reference}/comments
 */
export const publishTaskComment = (
  http: ApiRequestClient,
  { reference }: PublishTaskCommentParams,
  data: PublishTaskComment,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: PublishTaskCommentOkEnum;
      data: TaskCommentSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/board-tasks/${reference}/comments`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
