/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  DocumentRelationChange,
  EntitySaved,
  RelateDocumentForProjectOkEnum,
  RelateDocumentForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Прикрепить, изменить или открепить одну связь документа с проверкой ревизии; прочие связи и links сохраняются
 *
 * @tags entities
 * @name RelateDocumentForProject
 * @summary Прикрепить, изменить или открепить одну связь документа с проверкой ревизии; прочие связи и links сохраняются
 * @request POST:/api/v1/projects/{project}/entities/relate-document
 */
export const relateDocumentForProject = (
  http: ApiRequestClient,
  { project }: RelateDocumentForProjectParams,
  data: DocumentRelationChange,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: RelateDocumentForProjectOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/relate-document`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
