/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ProjectSettings,
  SaveProjectSettings,
  SaveProjectSettingsForProjectOkEnum,
  SaveProjectSettingsForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Сохранить текущие имя и slug проекта
 *
 * @tags context
 * @name SaveProjectSettingsForProject
 * @summary Сохранить текущие имя и slug проекта
 * @request PUT:/api/v1/projects/{project}/context/settings
 */
export const saveProjectSettingsForProject = (
  http: ApiRequestClient,
  { project }: SaveProjectSettingsForProjectParams,
  data: SaveProjectSettings,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: SaveProjectSettingsForProjectOkEnum;
      data: ProjectSettings;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/context/settings`,
    method: "PUT",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
