/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  ProductSaved,
  UpdateImplementation,
  UpdateProductImplementationOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить отдельную реализацию с проверкой её ревизии
 *
 * @tags product
 * @name UpdateProductImplementation
 * @summary Изменить отдельную реализацию с проверкой её ревизии
 * @request POST:/api/v1/product/implementations
 */
export const updateProductImplementation = (
  http: ApiRequestClient,
  data: UpdateImplementation,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateProductImplementationOkEnum;
      data: ProductSaved;
    },
    ApiFailure
  >({
    path: `/api/v1/product/implementations`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
