/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySaved,
  UpdateEntity,
  UpdateEntityForProjectOkEnum,
  UpdateEntityForProjectParams,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить содержание сущности по ключу или ID с проверкой ревизии
 *
 * @tags entities
 * @name UpdateEntityForProject
 * @summary Изменить содержание сущности по ключу или ID с проверкой ревизии
 * @request POST:/api/v1/projects/{project}/entities/update
 */
export const updateEntityForProject = (
  http: ApiRequestClient,
  { project }: UpdateEntityForProjectParams,
  data: UpdateEntity,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateEntityForProjectOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/projects/${project}/entities/update`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
