/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import type {
  ApiFailure,
  EntitySaved,
  UpdateEntity,
  UpdateEntityOkEnum,
} from "../data-contracts.js";
import type { ApiRequestClient, RequestParams } from "../http-client.js";
import { ContentType } from "../http-client.js";

/**
 * @description Изменить содержание сущности по ключу или ID с проверкой ревизии
 *
 * @tags entities
 * @name UpdateEntity
 * @summary Изменить содержание сущности по ключу или ID с проверкой ревизии
 * @request POST:/api/v1/entities/update
 */
export const updateEntity = (
  http: ApiRequestClient,
  data: UpdateEntity,
  params: RequestParams = {},
) =>
  http.request<
    {
      ok: UpdateEntityOkEnum;
      data: EntitySaved;
    },
    ApiFailure
  >({
    path: `/api/v1/entities/update`,
    method: "POST",
    body: data,
    type: ContentType.Json,
    format: "json",
    ...params,
  });
