/**
 * Generated by @gromlab/rest-api-codegen.
 * Do not edit manually. Regenerate the SDK from its OpenAPI specification.
 * https://github.com/gromlab-ru/rest-api-codegen
 */

import { changePlanStageForProject } from "./operations/change-plan-stage-for-project.js";
import { changePlanStage } from "./operations/change-plan-stage.js";
import { changePlanTasksForProject } from "./operations/change-plan-tasks-for-project.js";
import { changePlanTasks } from "./operations/change-plan-tasks.js";
import { changeTaskCriterionForProject } from "./operations/change-task-criterion-for-project.js";
import { changeTaskCriterion } from "./operations/change-task-criterion.js";
import { createBoardTaskForProject } from "./operations/create-board-task-for-project.js";
import { createBoardTask } from "./operations/create-board-task.js";
import { createEntityForProject } from "./operations/create-entity-for-project.js";
import { createEntity } from "./operations/create-entity.js";
import { createPlanForProject } from "./operations/create-plan-for-project.js";
import { createPlan } from "./operations/create-plan.js";
import { createReleaseForProject } from "./operations/create-release-for-project.js";
import { createRelease } from "./operations/create-release.js";
import { deleteEntityForProject } from "./operations/delete-entity-for-project.js";
import { deleteEntity } from "./operations/delete-entity.js";
import { describeEntityTypeForProject } from "./operations/describe-entity-type-for-project.js";
import { describeEntityType } from "./operations/describe-entity-type.js";
import { getApplicationProgressForProject } from "./operations/get-application-progress-for-project.js";
import { getApplicationProgress } from "./operations/get-application-progress.js";
import { getBoardBySlugForProject } from "./operations/get-board-by-slug-for-project.js";
import { getBoardBySlug } from "./operations/get-board-by-slug.js";
import { getBoardTaskForProject } from "./operations/get-board-task-for-project.js";
import { getBoardTaskLinksForProject } from "./operations/get-board-task-links-for-project.js";
import { getBoardTaskLinks } from "./operations/get-board-task-links.js";
import { getBoardTask } from "./operations/get-board-task.js";
import { getBoardTasksForProject } from "./operations/get-board-tasks-for-project.js";
import { getBoardTasks } from "./operations/get-board-tasks.js";
import { getBoardsForProject } from "./operations/get-boards-for-project.js";
import { getBoards } from "./operations/get-boards.js";
import { getContextForProject } from "./operations/get-context-for-project.js";
import { getContext } from "./operations/get-context.js";
import { getEntityForProject } from "./operations/get-entity-for-project.js";
import { getEntityHistoryForProject } from "./operations/get-entity-history-for-project.js";
import { getEntityHistory } from "./operations/get-entity-history.js";
import { getEntityKeySpacesForProject } from "./operations/get-entity-key-spaces-for-project.js";
import { getEntityKeySpaces } from "./operations/get-entity-key-spaces.js";
import { getEntityKeysForProject } from "./operations/get-entity-keys-for-project.js";
import { getEntityKeys } from "./operations/get-entity-keys.js";
import { getEntity } from "./operations/get-entity.js";
import { getFeatureProgressForProject } from "./operations/get-feature-progress-for-project.js";
import { getFeatureProgress } from "./operations/get-feature-progress.js";
import { getFullContextForProject } from "./operations/get-full-context-for-project.js";
import { getFullContext } from "./operations/get-full-context.js";
import { getGraphForProject } from "./operations/get-graph-for-project.js";
import { getGraphHistoryForProject } from "./operations/get-graph-history-for-project.js";
import { getGraphHistory } from "./operations/get-graph-history.js";
import { getGraph } from "./operations/get-graph.js";
import { getHealth } from "./operations/get-health.js";
import { getImplementationProgressForProject } from "./operations/get-implementation-progress-for-project.js";
import { getImplementationProgress } from "./operations/get-implementation-progress.js";
import { getPlanForProject } from "./operations/get-plan-for-project.js";
import { getPlanStageTasksForProject } from "./operations/get-plan-stage-tasks-for-project.js";
import { getPlanStageTasks } from "./operations/get-plan-stage-tasks.js";
import { getPlanStagesForProject } from "./operations/get-plan-stages-for-project.js";
import { getPlanStages } from "./operations/get-plan-stages.js";
import { getPlan } from "./operations/get-plan.js";
import { getPlanningCandidatesForProject } from "./operations/get-planning-candidates-for-project.js";
import { getPlanningCandidates } from "./operations/get-planning-candidates.js";
import { getPlansForProject } from "./operations/get-plans-for-project.js";
import { getPlans } from "./operations/get-plans.js";
import { getProductContextForProject } from "./operations/get-product-context-for-project.js";
import { getProductContext } from "./operations/get-product-context.js";
import { getProductEntitiesForProject } from "./operations/get-product-entities-for-project.js";
import { getProductEntities } from "./operations/get-product-entities.js";
import { getProductEntityForProject } from "./operations/get-product-entity-for-project.js";
import { getProductEntity } from "./operations/get-product-entity.js";
import { getProductOverviewForProject } from "./operations/get-product-overview-for-project.js";
import { getProductOverview } from "./operations/get-product-overview.js";
import { getProductProgressForProject } from "./operations/get-product-progress-for-project.js";
import { getProductProgress } from "./operations/get-product-progress.js";
import { getProductRecordsForProject } from "./operations/get-product-records-for-project.js";
import { getProductRecords } from "./operations/get-product-records.js";
import { getProductStateForProject } from "./operations/get-product-state-for-project.js";
import { getProductState } from "./operations/get-product-state.js";
import { getProjectSettingsForProject } from "./operations/get-project-settings-for-project.js";
import { getProjectSettings } from "./operations/get-project-settings.js";
import { getProjects } from "./operations/get-projects.js";
import { getReleaseForProject } from "./operations/get-release-for-project.js";
import { getReleasePlansForProject } from "./operations/get-release-plans-for-project.js";
import { getReleasePlans } from "./operations/get-release-plans.js";
import { getReleaseProgressForProject } from "./operations/get-release-progress-for-project.js";
import { getReleaseProgress } from "./operations/get-release-progress.js";
import { getRelease } from "./operations/get-release.js";
import { getReleasesForProject } from "./operations/get-releases-for-project.js";
import { getReleases } from "./operations/get-releases.js";
import { getScenarioProgressForProject } from "./operations/get-scenario-progress-for-project.js";
import { getScenarioProgress } from "./operations/get-scenario-progress.js";
import { getServerContext } from "./operations/get-server-context.js";
import { getTaskCommentForProject } from "./operations/get-task-comment-for-project.js";
import { getTaskComment } from "./operations/get-task-comment.js";
import { getTaskCommentsForProject } from "./operations/get-task-comments-for-project.js";
import { getTaskComments } from "./operations/get-task-comments.js";
import { getTaskCriteriaForProject } from "./operations/get-task-criteria-for-project.js";
import { getTaskCriteria } from "./operations/get-task-criteria.js";
import { getTaskCriterionForProject } from "./operations/get-task-criterion-for-project.js";
import { getTaskCriterion } from "./operations/get-task-criterion.js";
import { getTaskHistoryEventForProject } from "./operations/get-task-history-event-for-project.js";
import { getTaskHistoryEvent } from "./operations/get-task-history-event.js";
import { getTaskHistoryForProject } from "./operations/get-task-history-for-project.js";
import { getTaskHistory } from "./operations/get-task-history.js";
import { getTaskPlanMembershipsForProject } from "./operations/get-task-plan-memberships-for-project.js";
import { getTaskPlanMemberships } from "./operations/get-task-plan-memberships.js";
import { getTaskProgressForProject } from "./operations/get-task-progress-for-project.js";
import { getTaskProgress } from "./operations/get-task-progress.js";
import { getWorkPlanProgressForProject } from "./operations/get-work-plan-progress-for-project.js";
import { getWorkPlanProgress } from "./operations/get-work-plan-progress.js";
import { linkBoardTaskForProject } from "./operations/link-board-task-for-project.js";
import { linkBoardTask } from "./operations/link-board-task.js";
import { linkEntityTaskForProject } from "./operations/link-entity-task-for-project.js";
import { linkEntityTask } from "./operations/link-entity-task.js";
import { listEntitiesForProject } from "./operations/list-entities-for-project.js";
import { listEntities } from "./operations/list-entities.js";
import { listEntityTypesForProject } from "./operations/list-entity-types-for-project.js";
import { listEntityTypes } from "./operations/list-entity-types.js";
import { moveBoardTaskForProject } from "./operations/move-board-task-for-project.js";
import { moveBoardTask } from "./operations/move-board-task.js";
import { moveEntityTaskForProject } from "./operations/move-entity-task-for-project.js";
import { moveEntityTask } from "./operations/move-entity-task.js";
import { mutateGraphForProject } from "./operations/mutate-graph-for-project.js";
import { mutateGraph } from "./operations/mutate-graph.js";
import { mutateProductForProject } from "./operations/mutate-product-for-project.js";
import { mutateProduct } from "./operations/mutate-product.js";
import { previewEntityDeletionForProject } from "./operations/preview-entity-deletion-for-project.js";
import { previewEntityDeletion } from "./operations/preview-entity-deletion.js";
import { previewReleaseForProject } from "./operations/preview-release-for-project.js";
import { previewRelease } from "./operations/preview-release.js";
import { publishTaskCommentForProject } from "./operations/publish-task-comment-for-project.js";
import { publishTaskComment } from "./operations/publish-task-comment.js";
import { registerProject } from "./operations/register-project.js";
import { renameEntityKeyForProject } from "./operations/rename-entity-key-for-project.js";
import { renameEntityKey } from "./operations/rename-entity-key.js";
import { resolveEntityForProject } from "./operations/resolve-entity-for-project.js";
import { resolveEntity } from "./operations/resolve-entity.js";
import { saveProjectSettingsForProject } from "./operations/save-project-settings-for-project.js";
import { saveProjectSettings } from "./operations/save-project-settings.js";
import { transferPlanTaskForProject } from "./operations/transfer-plan-task-for-project.js";
import { transferPlanTask } from "./operations/transfer-plan-task.js";
import { transitionPlanForProject } from "./operations/transition-plan-for-project.js";
import { transitionPlan } from "./operations/transition-plan.js";
import { transitionReleaseForProject } from "./operations/transition-release-for-project.js";
import { transitionRelease } from "./operations/transition-release.js";
import { unregisterProject } from "./operations/unregister-project.js";
import { updateBoardTaskForProject } from "./operations/update-board-task-for-project.js";
import { updateBoardTask } from "./operations/update-board-task.js";
import { updateEntityForProject } from "./operations/update-entity-for-project.js";
import { updateEntity } from "./operations/update-entity.js";
import { updatePlanForProject } from "./operations/update-plan-for-project.js";
import { updatePlan } from "./operations/update-plan.js";
import { updateProductImplementationForProject } from "./operations/update-product-implementation-for-project.js";
import { updateProductImplementation } from "./operations/update-product-implementation.js";
import { updateReleaseForProject } from "./operations/update-release-for-project.js";
import { updateRelease } from "./operations/update-release.js";
import { validateProjectForProject } from "./operations/validate-project-for-project.js";
import { validateProject } from "./operations/validate-project.js";
import { watchEventsForProject } from "./operations/watch-events-for-project.js";
import { watchEvents } from "./operations/watch-events.js";

export const operationsTree = {
  health: {
    getHealth: getHealth,
  },
  server: {
    getServerContext: getServerContext,
  },
  projects: {
    getProjects: getProjects,
    registerProject: registerProject,
    unregisterProject: unregisterProject,
  },
  context: {
    getContext: getContext,
    getProjectSettings: getProjectSettings,
    saveProjectSettings: saveProjectSettings,
    getContextForProject: getContextForProject,
    getProjectSettingsForProject: getProjectSettingsForProject,
    saveProjectSettingsForProject: saveProjectSettingsForProject,
  },
  project: {
    validateProject: validateProject,
    validateProjectForProject: validateProjectForProject,
  },
  product: {
    getProductEntities: getProductEntities,
    getProductEntity: getProductEntity,
    updateProductImplementation: updateProductImplementation,
    getProductState: getProductState,
    getProductOverview: getProductOverview,
    getProductRecords: getProductRecords,
    mutateProduct: mutateProduct,
    getProductContext: getProductContext,
    getProductEntitiesForProject: getProductEntitiesForProject,
    getProductEntityForProject: getProductEntityForProject,
    updateProductImplementationForProject:
      updateProductImplementationForProject,
    getProductStateForProject: getProductStateForProject,
    getProductOverviewForProject: getProductOverviewForProject,
    getProductRecordsForProject: getProductRecordsForProject,
    mutateProductForProject: mutateProductForProject,
    getProductContextForProject: getProductContextForProject,
  },
  progress: {
    getWorkPlanProgress: getWorkPlanProgress,
    getReleaseProgress: getReleaseProgress,
    getTaskProgress: getTaskProgress,
    getImplementationProgress: getImplementationProgress,
    getScenarioProgress: getScenarioProgress,
    getFeatureProgress: getFeatureProgress,
    getApplicationProgress: getApplicationProgress,
    getProductProgress: getProductProgress,
    getWorkPlanProgressForProject: getWorkPlanProgressForProject,
    getReleaseProgressForProject: getReleaseProgressForProject,
    getTaskProgressForProject: getTaskProgressForProject,
    getImplementationProgressForProject: getImplementationProgressForProject,
    getScenarioProgressForProject: getScenarioProgressForProject,
    getFeatureProgressForProject: getFeatureProgressForProject,
    getApplicationProgressForProject: getApplicationProgressForProject,
    getProductProgressForProject: getProductProgressForProject,
  },
  plans: {
    getPlans: getPlans,
    createPlan: createPlan,
    getTaskPlanMemberships: getTaskPlanMemberships,
    getPlanningCandidates: getPlanningCandidates,
    getPlan: getPlan,
    getPlanStages: getPlanStages,
    changePlanStage: changePlanStage,
    getPlanStageTasks: getPlanStageTasks,
    updatePlan: updatePlan,
    transitionPlan: transitionPlan,
    changePlanTasks: changePlanTasks,
    transferPlanTask: transferPlanTask,
    getPlansForProject: getPlansForProject,
    createPlanForProject: createPlanForProject,
    getTaskPlanMembershipsForProject: getTaskPlanMembershipsForProject,
    getPlanningCandidatesForProject: getPlanningCandidatesForProject,
    getPlanForProject: getPlanForProject,
    getPlanStagesForProject: getPlanStagesForProject,
    changePlanStageForProject: changePlanStageForProject,
    getPlanStageTasksForProject: getPlanStageTasksForProject,
    updatePlanForProject: updatePlanForProject,
    transitionPlanForProject: transitionPlanForProject,
    changePlanTasksForProject: changePlanTasksForProject,
    transferPlanTaskForProject: transferPlanTaskForProject,
  },
  releases: {
    getReleases: getReleases,
    createRelease: createRelease,
    previewRelease: previewRelease,
    getRelease: getRelease,
    getReleasePlans: getReleasePlans,
    updateRelease: updateRelease,
    transitionRelease: transitionRelease,
    getReleasesForProject: getReleasesForProject,
    createReleaseForProject: createReleaseForProject,
    previewReleaseForProject: previewReleaseForProject,
    getReleaseForProject: getReleaseForProject,
    getReleasePlansForProject: getReleasePlansForProject,
    updateReleaseForProject: updateReleaseForProject,
    transitionReleaseForProject: transitionReleaseForProject,
  },
  boards: {
    getBoards: getBoards,
    getBoardBySlug: getBoardBySlug,
    getBoardsForProject: getBoardsForProject,
    getBoardBySlugForProject: getBoardBySlugForProject,
  },
  kanban: {
    getBoardTasks: getBoardTasks,
    createBoardTask: createBoardTask,
    getBoardTask: getBoardTask,
    getBoardTaskLinks: getBoardTaskLinks,
    linkBoardTask: linkBoardTask,
    getTaskCriteria: getTaskCriteria,
    changeTaskCriterion: changeTaskCriterion,
    getTaskComments: getTaskComments,
    publishTaskComment: publishTaskComment,
    getTaskComment: getTaskComment,
    getTaskHistory: getTaskHistory,
    getTaskHistoryEvent: getTaskHistoryEvent,
    getTaskCriterion: getTaskCriterion,
    updateBoardTask: updateBoardTask,
    moveBoardTask: moveBoardTask,
    getBoardTasksForProject: getBoardTasksForProject,
    createBoardTaskForProject: createBoardTaskForProject,
    getBoardTaskForProject: getBoardTaskForProject,
    getBoardTaskLinksForProject: getBoardTaskLinksForProject,
    linkBoardTaskForProject: linkBoardTaskForProject,
    getTaskCriteriaForProject: getTaskCriteriaForProject,
    changeTaskCriterionForProject: changeTaskCriterionForProject,
    getTaskCommentsForProject: getTaskCommentsForProject,
    publishTaskCommentForProject: publishTaskCommentForProject,
    getTaskCommentForProject: getTaskCommentForProject,
    getTaskHistoryForProject: getTaskHistoryForProject,
    getTaskHistoryEventForProject: getTaskHistoryEventForProject,
    getTaskCriterionForProject: getTaskCriterionForProject,
    updateBoardTaskForProject: updateBoardTaskForProject,
    moveBoardTaskForProject: moveBoardTaskForProject,
  },
  graph: {
    getGraph: getGraph,
    mutateGraph: mutateGraph,
    getFullContext: getFullContext,
    getGraphHistory: getGraphHistory,
    getGraphForProject: getGraphForProject,
    mutateGraphForProject: mutateGraphForProject,
    getFullContextForProject: getFullContextForProject,
    getGraphHistoryForProject: getGraphHistoryForProject,
  },
  entities: {
    listEntityTypes: listEntityTypes,
    previewEntityDeletion: previewEntityDeletion,
    deleteEntity: deleteEntity,
    describeEntityType: describeEntityType,
    listEntities: listEntities,
    createEntity: createEntity,
    getEntity: getEntity,
    resolveEntity: resolveEntity,
    getEntityKeys: getEntityKeys,
    getEntityKeySpaces: getEntityKeySpaces,
    getEntityHistory: getEntityHistory,
    updateEntity: updateEntity,
    renameEntityKey: renameEntityKey,
    moveEntityTask: moveEntityTask,
    linkEntityTask: linkEntityTask,
    listEntityTypesForProject: listEntityTypesForProject,
    previewEntityDeletionForProject: previewEntityDeletionForProject,
    deleteEntityForProject: deleteEntityForProject,
    describeEntityTypeForProject: describeEntityTypeForProject,
    listEntitiesForProject: listEntitiesForProject,
    createEntityForProject: createEntityForProject,
    getEntityForProject: getEntityForProject,
    resolveEntityForProject: resolveEntityForProject,
    getEntityKeysForProject: getEntityKeysForProject,
    getEntityKeySpacesForProject: getEntityKeySpacesForProject,
    getEntityHistoryForProject: getEntityHistoryForProject,
    updateEntityForProject: updateEntityForProject,
    renameEntityKeyForProject: renameEntityKeyForProject,
    moveEntityTaskForProject: moveEntityTaskForProject,
    linkEntityTaskForProject: linkEntityTaskForProject,
  },
  events: {
    watchEvents: watchEvents,
    watchEventsForProject: watchEventsForProject,
  },
} as const;

export type OperationsTree = typeof operationsTree;
